[package]
name = "hop"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bytes = "1.6.1"
clap = { version = "4.5.11", features = ["derive"] }
prost = "0.13.1"
serde = { version = "1.0.204", features = ["serde_derive"] }
serde_json = "1.0.121"
