[package]
name = "hop-scip-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hop"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.11", features = ["derive"] }
serde = { version = "1.0.204", features = ["serde_derive"] }
serde_json = "1.0.121"
hop-scip = { path = "../hop-scip" }
